name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - mlflow
  - numpy
  - ipython
  - notebook
  - jupyterlab
  - cookiecutter
  - hydra-core
  - matplotlib
  - pandas
  - git
  - pip=20.3.3
  - pip:
      - wandb